"""empty message

Revision ID: 225bbcceb744
Revises: 1bcaf47607ab
Create Date: 2018-08-22 18:22:56.408305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '225bbcceb744'
down_revision = '1bcaf47607ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('coach', sa.Integer(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coach'], ['coach.id'], ),
    sa.ForeignKeyConstraint(['team'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memo')
    # ### end Alembic commands ###
